# Generated by Django 4.0.4 on 2022-06-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('age', models.PositiveIntegerField(default=None)),
                ('rank', models.PositiveBigIntegerField(blank=True, null=True)),
                ('still_active', models.BooleanField(default=True)),
                ('styles', models.ManyToManyField(related_name='surfers', to='styles.style')),
            ],
        ),
    ]
