# Generated by Django 4.0.4 on 2022-06-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surfers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='surfers.surfer')),
            ],
        ),
    ]
